// Photo albums. Each album becomes one tile on /photos/; opening it reveals a
// carousel of its images. Add a new object here to add an album.
//   title  — album name (shown under the tile)
//   year   — shown muted next to the title
//   note   — optional link to a related note (rendered inside the carousel)
//   cover  — optional cover image; defaults to the first image
//   images — the photos, in carousel order
export default [
  {
    title: "Lamington National Park",
    year: 2024,
    note: "/notes/a-day-at-lamington-national-park/",
    images: [
      "/assets/images/2024/lamington-12.jpeg",
      "/assets/images/2024/lamington-14.jpeg",
      "/assets/images/2024/lamington-9.jpeg",
      "/assets/images/2024/lamington-4.jpeg",
      "/assets/images/2024/lamington-7.jpeg",
      "/assets/images/2024/lamington-3.jpeg",
      "/assets/images/2024/lamington-10.jpeg",
      "/assets/images/2024/lamington-13.jpeg",
      "/assets/images/2024/lamington-6.jpeg",
      "/assets/images/2024/lamington-5.jpeg",
      "/assets/images/2024/lamington-11.jpeg",
    ],
  },
  {
    title: "Byron Bay",
    year: 2024,
    note: "/notes/byron-bay-in-rain-and-in-head/",
    images: [
      "/assets/images/2024/IMG_0841.jpeg",
      "/assets/images/2024/IMG_0826.jpeg",
      "/assets/images/2024/IMG_0851.jpeg",
      "/assets/images/2024/IMG_0871.jpeg",
    ],
  },
  {
    title: "MagFlora",
    year: 2021,
    note: "/notes/mathematics-of-magnificent-flora/",
    cover: "/assets/images/2021/magflora-00.jpg",
    images: [
      "/assets/images/2021/magflora-00.jpg",
      "/assets/images/2021/magflora-01.jpg",
      "/assets/images/2021/magflora-02.jpg",
      "/assets/images/2021/magflora-03.jpg",
      "/assets/images/2021/magflora-04.jpg",
      "/assets/images/2021/magflora-05.jpg",
      "/assets/images/2021/magflora-06.jpg",
      "/assets/images/2021/magflora-07.jpg",
      "/assets/images/2021/magflora-08.jpg",
      "/assets/images/2021/magflora-09.jpg",
      "/assets/images/2021/magflora-10.jpg",
    ],
  },
  {
    title: "Mathscapes Identity",
    year: 2021,
    note: "/notes/mathscapes-identity/",
    cover: "/assets/images/2023/logomark-construction.svg",
    images: [
      "/assets/images/2023/logomark-construction.svg",
      "/assets/images/2023/wordmark-construction.svg",
    ],
  },
  {
    title: "Deconstructing Algorithms",
    year: 2020,
    note: "/notes/deconstructing-algorithms/",
    cover: "/assets/images/2020/2020.jpg",
    links: [
      {
        label: "Oribaka: building the language",
        url: "https://www.youtube.com/watch?v=_KFUswH6WJM",
      },
      {
        label: "Oribaka: trying it out",
        url: "https://www.youtube.com/watch?v=P2RBCs36yzc",
      },
    ],
    images: [
      "/assets/images/2020/2020.jpg",
      "/assets/images/2020/1.jpg",
      "/assets/images/2020/2.jpg",
      "/assets/images/2020/3.jpg",
      "/assets/images/2020/4.jpg",
      "/assets/images/2020/5.jpg",
    ],
  },
  {
    title: "Making with Algorithms",
    year: 2019,
    note: "/notes/making-with-algorithms/",
    cover: "/assets/images/2019/mwa_15.jpg",
    images: [
      "/assets/images/2019/mwa_1.jpg",
      "/assets/images/2019/mwa_2.jpg",
      "/assets/images/2019/mwa_3.jpg",
      "/assets/images/2019/mwa_4.jpg",
      "/assets/images/2019/mwa_5.jpg",
      "/assets/images/2019/mwa_6.jpg",
      "/assets/images/2019/mwa_7.jpg",
      "/assets/images/2019/mwa_8.jpg",
      "/assets/images/2019/mwa_9.jpg",
      "/assets/images/2019/mwa_10.jpg",
      "/assets/images/2019/mwa_11.jpg",
      "/assets/images/2019/mwa_12.jpg",
      "/assets/images/2019/mwa_13.jpg",
      "/assets/images/2019/mwa_14.jpg",
      "/assets/images/2019/mwa_15.jpg",
      "/assets/images/2019/mwa_16.jpg",
      "/assets/images/2019/mwa_17.jpg",
      "/assets/images/2019/mwa_18.jpg",
      "/assets/images/2019/mwa_19.jpg",
      "/assets/images/2019/mwa_20.jpg",
      "/assets/images/2019/mwa_21.jpg",
      "/assets/images/2019/mwa_22.jpg",
      "/assets/images/2019/mwa_23.jpg",
      "/assets/images/2019/mwa_24.jpg",
      "/assets/images/2019/mwa_25.jpg",
      "/assets/images/2019/mwa_26.jpg",
      "/assets/images/2019/mwa_27.jpg",
      "/assets/images/2019/mwa_29.jpg",
      "/assets/images/2019/mwa_30.jpg",
    ],
  },
  {
    title: "Tangible Computing",
    year: 2019,
    note: "/notes/tangible-computing/",
    images: [
      "/assets/images/2019/tangcompA_1.jpeg",
      "/assets/images/2019/tangcompA_2.jpeg",
      "/assets/images/2019/tangcompA_3.jpeg",
      "/assets/images/2019/tangcompA_4.jpeg",
      "/assets/images/2019/tangcompA_5.jpeg",
      "/assets/images/2019/tangcompA_6.jpeg",
    ],
  },
  {
    title: "ReRide",
    year: 2019,
    note: "/notes/reride/",
    cover: "/assets/images/2019/reride-new.jpg",
    images: [
      "/assets/images/2019/reride-new.jpg",
      "/assets/images/2018/2.jpg",
      "/assets/images/2018/3.jpg",
    ],
  },
  {
    title: "Digital Making",
    year: 2017,
    note: "/notes/digital-making/",
    images: [
      "/assets/images/2017/1.jpg",
      "/assets/images/2017/2.jpg",
      "/assets/images/2017/3.jpg",
      "/assets/images/2017/4.jpg",
      "/assets/images/2017/5.jpg",
      "/assets/images/2017/6.jpg",
      "/assets/images/2017/7.jpg",
      "/assets/images/2017/8.jpg",
      "/assets/images/2017/9.jpg",
    ],
  },
  {
    title: "Interact 2017",
    year: 2017,
    note: "/notes/interact-2017/",
    cover: "/assets/images/2017/interact_1.jpg",
    images: [
      "/assets/images/2017/interact_1.jpg",
      "/assets/images/2017/interact_2.jpg",
      "/assets/images/2017/interact_3.jpg",
      "/assets/images/2017/interact_4.jpg",
      "/assets/images/2017/interact_5.jpg",
      "/assets/images/2017/interact_6.jpg",
      "/assets/images/2017/interact_7.jpg",
    ],
  },
  {
    title: "Topcoder Open 2017",
    year: 2017,
    note: "/notes/tco17-india-regionals/",
    cover: "/assets/images/2017/group.jpg",
    images: [
      "/assets/images/2017/workshop.jpg",
      "/assets/images/2017/image7.jpg",
      "/assets/images/2017/image3.jpg",
      "/assets/images/2017/image12.jpg",
      "/assets/images/2017/award.jpg",
      "/assets/images/2017/group.jpg",
    ],
  },
];
